### ISSUE TITLE
Send audio

### ISSUE THREAD

**Issue by off112a** [synesthesiam/homeassistant-satellite#26]
Hi,

Is it possible to send a wav file to play on the the satellite, like a doorbell or alarm?

**Comment by chatziko** [comment]
The satellite can play feedback (awake / done) sounds as explained in the README, but it cannot play a sound at an arbitrary moment.

IMHO the latter is probably outside the scope of a satellite, it has little to do with voice and there are lots of other ways to do it in HA ([MPD](https://www.home-assistant.io/integrations/mpd/) or an ssh script are probably the easiest).

**Comment by synesthesiam** [comment]
That should come back in the TTS response though, shouldn't it @collinstork ?

**Comment by collinstork** [comment]
It does for some, but I believe that for some responses, google returns html instead of plain text so for this
```
service: google_assistant_sdk.send_text_command
data:
  command: how tall is mark hamill
  media_player: media_player.living_room
```
  the response is 
```
  responses:
  - text: null
```
but the audio response is still returned & played thru the media player specified.
